[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gpu-graphlib"
version = "0.1.0"
description = "ctypes bindings for libarboqllib"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
package-dir = {"" = "bindings/python/src"}

[tool.setuptools.packages.find]
where = ["bindings/python/src"]

[tool.setuptools.package-data]
arboqllib = [".lib/libarboqllib.so", ".lib/*.so.*"]